name: Third Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Salaam
        run: echo "Salaam"
      - name: Print Bye
        run: echo "Bye!"
